name: .NET Core

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Build (Release)
      run: dotnet build --configuration Release

    - name: Test (Release)
      run: dotnet test --configuration Release

    - name: Pack (Release)
      run: dotnet pack Raptorious.SharpMt940Lib --configuration Release

    - name: Publish
      if: github.event_name == 'push'
      run: |      
          if ( "${{github.ref}}" -match "^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$" ) {
              dotnet nuget push Raptorious.SharpMt940Lib\bin\Release\*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}}
          } else {
              echo "publish is only enabled by tagging with a release tag"
          }
